include classpath("application.conf")

queues {
  local-periodic-tasks {
    defaultVisibilityTimeout = 300 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
  local-govuk-alerts {
    defaultVisibilityTimeout = 300 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
  local-broadcast-tasks {
    defaultVisibilityTimeout = 300 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
}
